### PR TITLE
Compiling Leveldown for Android x86

### PR DESCRIPTION
**Pull request by luandro**
This change was originally made by [https://github.com/jaimecbernardo](https://github.com/jaimecbernardo):

> For `x86`, the NDK doesn't seem to be able to provide 128 bit intrinsics, so you need to replace this line in `deps/snappy/snappy-1.1.4/snappy.cc` https://github.com/Level/leveldown/blob/8b03831f1d826c326c14555e471f45bffd817fe9/deps/snappy/snappy-1.1.4/snappy.cc#L98
Replace:
```
#ifdef __SSE2__
```
with
```
#if defined(__SSE2__) && !(defined(__ANDROID__) && defined(__i386__))
```

### CODE REVIEW

**Comment by luandro** [comment]
@ralphtheninja could you take a look at this? It's a simple fix for supporting Android x86 devices.

**Comment by ralphtheninja** [comment]
Changes like this _should_ really go into upstream. Once we update `leveldb` it will be gone.

cc @vweevers @juliangruber WDYT?

**Comment by vweevers** [comment]
We have had patches in the past. At least:

- leveldb 1.20: https://github.com/Level/leveldown/pull/353/commits/47d65af669888772e327b3ffdc324fe8adfdfba4
- leveldb 1.19: https://github.com/Level/leveldown/pull/299/commits/21dc91ebe64725c451719be0968941f4bf012be9 and earlier versions: https://github.com/Level/leveldown/commit/09af2a750920b106f3abedc9a98fa438f359624c

As far as I can see, we never kept a record of `.patch` files. Even if we did, they're not gonna apply cleanly, esp. if we get more of them. I expect it to be a burden.

But if Google is too slow in accepting changes, or refuses them for non-technical reasons, we can consider taking small patches here. As long as it's understood that it's not on the maintainers of `leveldown` to update them - and that they are likely to break in future releases.

**Comment by ralphtheninja** [comment]
@vweevers We can try to keep track of them from now on and we should be able to generate `.patch` files.

**Comment by vweevers** [comment]
@ralphtheninja open an issue :)

**Comment by ralphtheninja** [comment]
3.0.2

**Pull request merged**
