### PR TITLE
add node v4.0.0 (abi 46)

### PR DESCRIPTION
**Pull request by ralphtheninja**

### CODE REVIEW

**Comment by mafintosh** [comment]
:+1:

**Comment by No9** [comment]
@ralphtheninja  @mafintosh 
Who is going to run what then? :) 
I can do the win X64 if someone wants to do the Linux/Macs

**Comment by mafintosh** [comment]
@No9 I can do everything except win64. If you want to you can have win32 as well? (since you're already doing one win build). If you don't have that setup I can still do the win32 builds

**Comment by ralphtheninja** [comment]
I'll do arm (Raspberry PI b)

**Comment by No9** [comment]
@mafintosh I might have an old laptop I can revive will let you know tomorrow but your suggestion makes sense
Are we going to build master or drop this patch on 1.4.1?

**Comment by No9** [comment]
Actually wasn't thinking there
Yes I can take the 32 as well

**Comment by ralphtheninja** [comment]
I build on tags, just to be sure, even though I know now that building on master should be safe.

**Comment by ralphtheninja** [comment]
decentralized building! :tada:

**Comment by mafintosh** [comment]
linux, arm and mac builds are uploaded now.

**Comment by juliangruber** [comment]
kick ass!

**Comment by No9** [comment]
Yeah win-x64 is up too. 
Will get illumOS and win 32 in place tonight/tomorrow.

**Comment by ralphtheninja** [comment]
@No9 Nice! Did you rebuild x64 for all abis?

**Pull request merged**
