### PR TITLE
appveyor: remove node 5 and 7

### PR DESCRIPTION
**Pull request by ralphtheninja**
Gah. Forgot to update `AppVeyor`.

### CODE REVIEW

**Comment by vweevers** [comment]
Oops.

**Comment by ralphtheninja** [comment]
No super biggie. Would be nice with a tool that checked appveyor.yml and .travis.yml to make sure they are consistent :)

**Comment by vweevers** [comment]
You read my mind :)

**Comment by ralphtheninja** [comment]
I'll hack something up in the coming days.

**Comment by ralphtheninja** [comment]
@vweevers The way we write different node versions in `appveyor.yml` for `leveldown`, is that the canonical way of doing it or are there other ways of specifying the versions? I know for example that for `travis` you can specify node versions using both `node_js` and also through a matrix.

**Comment by vweevers** [comment]
I'd say yes, it's canonical. AppVeyor doesn't have a "shortcut" like `node_js`. And while people can use a different name for the env var (`nodejs_version`) if they want to, or use some custom script, I reckon most people won't as this is the method used in AppVeyor's docs.

**Comment by vweevers** [comment]
By the way it would be awesome if your tool also warns against EOL node versions.

**Comment by ralphtheninja** [comment]
I'm calling it `verify-travis-appveyor`. Will publish tomorrow or tonight.

**Comment by ralphtheninja** [comment]
@vweevers Should it warn or error?

**Comment by vweevers** [comment]
If node versions are inconsistent, it should error. For EOL versions, I'm not sure. Because that would affect every PR.

**Comment by vweevers** [comment]
Hmm could also employ it as a prepublish script, rather than a test script. Then it doesn't affect CI of unrelated PR's.

**Comment by ralphtheninja** [comment]
Aye, it should probably only warn on EOL versions. You could also have a flag that says to treat warnings as errors, if you really want it to error. It should be ok to target EOL node versions if you want to.

**Comment by ralphtheninja** [comment]
https://github.com/ralphtheninja/verify-travis-appveyor

Will add the lts stuff later.

**Comment by ralphtheninja** [comment]
> Hmm could also employ it as a prepublish script, rather than a test script. Then it doesn't affect CI of unrelated PR's.

@vweevers I thought some more about this. Why would this be a problem? I think I'd prefer to have this as a test to avoid having `prebuild-ci` building versions before we do `npm publish`. For example, if I change `.travis.yml` and make a PR it will be caught by tests and the test will only fail if a node version has changed in `.travis.yml` or `appveyor.yml` which makes them inconsistent.

**Comment by ralphtheninja** [comment]
Gotcha! Then we're on the same page 😄

**Pull request merged**
