### PR TITLE
IBM System Z (s390x architecture) support for deps/level-db

### PR DESCRIPTION
**Pull request by kycfeel**
This allows IBM System Z (s390x) to build the `leveldown` during the `npm install`.

### CODE REVIEW

**Comment by No9** [comment]
Thanks @kycfeel - As this project uses travis can I suggest adding Z to the CI config - https://blog.travis-ci.com/2019-11-12-multi-cpu-architecture-ibm-power-ibm-z this should help the project team validate the change.

**Comment by kycfeel** [comment]
@No9 Hey. I just added an `s390x` support on the `.travis.yml` file. Not sure this gonna work tho.

**Comment by kycfeel** [comment]
Looks like it has been failed cause there's no binary version of electron available for the s390x arch 🤔.

```
HTTPError: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v11.2.0/electron-v11.2.0-linux-s390x.zip
```

**Comment by vweevers** [comment]
The electron download can be skipped with `ELECTRON_SKIP_BINARY_DOWNLOAD=1`. We do the same on FreeBSD:

https://github.com/Level/leveldown/blob/a7893e44c9732132f0a938128011ecc240f480dc/.cirrus.yml#L8-L10

**Comment by kycfeel** [comment]
It passed the electron download issue, but now getting something else during the test 🥺.

Any idea how to solve this?

```
 test custom _serialize*# test approximateSize()
  ok 1230 undefinednode: ../deps/snappy/snappy/snappy.cc:509: char* snappy::internal::CompressFragment(const char*, size_t, char*, snappy::uint16*, int): Assertion `0 == memcmp(base, candidate, matched)' failed.
Aborted (core dumped)
✓ test approximateSize()1231 no plan found
⨯ fail  1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@5.6.0 test: `standard && (nyc -s tape test/*-test.js | faucet) && nyc report`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@5.6.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2021-01-18T13_43_43_019Z-debug.log
The command "if [[ ! -z "$TEST" ]]; then npm run test; fi" exited with 1.
```

**Pull request closed without merging**
