### PR TITLE
tap -> tape + faucet

### PR DESCRIPTION
**Pull request by ralphtheninja**

### CODE REVIEW

**Comment by mcollina** [comment]
:+1:

**Comment by juliangruber** [comment]
otherwise lgtm :)

**Comment by juliangruber** [comment]
oh wow

```bash
./node_modules/.bin/tape test/*.js
TAP version 13
# test ended iterator
Segmentation fault: 11
```

**Comment by juliangruber** [comment]
yeah, and:

```bash
./node_modules/.bin/tape test/*-test.js | ./node_modules/.bin/faucet
✓ test ended iterator
✓ test non-ended iterator
✓ test multiple non-ended iterators
✓ test ending iterators
✓ test argument-less destroy() throws
✓ test callback-less, 1-arg, destroy() throws
✓ test destroy non-existant directory
✓ test destroy non leveldb directory
✓ test destroy() cleans and removes leveldb-only dir
✓ test destroy() cleans and removes only leveldb parts of a dir
✓ setUp common
✓ setUp db
✓ test argument-less getProperty() throws
✓ test non-string getProperty() throws
✓ test invalid getProperty() returns empty string
✓ test invalid getProperty("leveldb.num-files-at-levelN") returns numbers
✓ test invalid getProperty("leveldb.stats")
✓ test invalid getProperty("leveldb.sstables")
✓ tearDown
✓ setUp common
✓ setUp db
✓ try to create an iterator with a blown stack
✓ iterate over a large iterator with a large watermark
✓ tearDown
✓ test port-libuv is being used
✓ test argument-less repair() throws
✓ test callback-less, 1-arg, repair() throws
✓ test repair non-existant directory returns error
✓ test repair() compacts
# tests 66
# pass  66
✓ ok
```

**Comment by ralphtheninja** [comment]
@juliangruber What seems correct? There are several hundreds of tests missing.

**Comment by ralphtheninja** [comment]
Seems some files doesn't work with tape. Not sure why. I get test output if I run:

```
$ node test/approximate-size-test.js
```

but not if I run

```
$ ./node_modules/.bin/tape test/approximate-size-test.js
```

/cc @substack Know what's going on here?

**Comment by juliangruber** [comment]
that's expected, see https://github.com/Level/leveldown/blob/master/test/approximate-size-test.js#L6. why do we have this line anyway?

**Comment by juliangruber** [comment]
(that's expected because tape `require()`s test files iirc)

**Comment by ralphtheninja** [comment]
@juliangruber Aye, just noticed. I'm removing them. Updating PR soon.

**Comment by ralphtheninja** [comment]
newoutput

**Comment by juliangruber** [comment]
+1

**Comment by juliangruber** [comment]
except: is someone `require()`ing the leveldown tests inside another module? @Level/owners

**Comment by ralphtheninja** [comment]
Double checked that all tests were running. Squashed commits.

**Comment by ralphtheninja** [comment]
In fact tap reported 712 tests, but it seems tap reports the wrong number of tests. If you just run any .js file with tap it will report `1/1` even though the file didn't have any tests in it (which was the case with `make-test.js`)

**Comment by ralphtheninja** [comment]
```
$ npm publish
+ leveldown@1.0.3
```

**Pull request merged**
