### PR TITLE
remove unsupported versions

### PR DESCRIPTION
**Pull request by ralphtheninja**
I'm going to re-run this on travis until it fails.

### CODE REVIEW

**Comment by ralphtheninja** [comment]
Watch me sit for 100 hours and gettings no fails :grinning:

**Comment by rvagg** [comment]
lgtm

**Comment by juliangruber** [comment]
@ralphtheninja taking one for the team, give this man a :cookie: !

**Comment by ralphtheninja** [comment]
20 runs and still no fails. Lets just merge this and as soon as something is borked with travis, remember to save the output and post to the travis issue!

**Pull request merged**
