### PR TITLE
level-hyper: merged v0.10 branch

### PR DESCRIPTION
**Pull request by ralphtheninja**
I merged the `v0.10` branch from @mcollina into `hyper-leveldb` so `level-hyper` can be functional with `iojs` as well. I'm not entirely sure this is the correct way to handle it, so please feel free to give some feedback on this.

Also, the `port-libuv-fix-test.js` does not pass, but it didn't pass before this merge either. Is it even relevant on this branch? If not, perhaps we should remove it.

### CODE REVIEW

**Comment by hij1nx** [comment]
This looks great! +1 Any reason not to merge??

**Comment by hij1nx** [comment]
@rvagg bump

**Comment by juliangruber** [comment]
i'm not really qialified to review, but lgtm

**Comment by mcollina** [comment]
LGTM from me. However @ralphtheninja does it works on 0.10, 0.12 and iojs?

**Comment by ralphtheninja** [comment]
@mcollina I'll make some tests today.

**Comment by juliangruber** [comment]
Results of testing on my mac:

On 0.10.38:

```
$ npm install
...
> node-gyp rebuild

make: *** No rule to make target `Release/obj.target/leveldb/deps/leveldb/leveldb-hyper/util/bloom.o', needed by `Release/leveldb.a'.  Stop.
```

On 0.12.1:

```
$ npm install
...
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: *** No rule to make target `Release/obj.target/leveldb/deps/leveldb/leveldb-hyper/util/bloom.o', needed by `Release/leveldb.a'.  Stop.
```

On iojs-1.6.2:

```
$ npm install
...
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: *** No rule to make target `Release/obj.target/leveldb/deps/leveldb/leveldb-hyper/util/bloom.o', needed by `Release/leveldb.a'.  Stop.
```

**Comment by ralphtheninja** [comment]
@juliangruber You need to `git submodule update --init` to get the hyperdex dependencies

**Comment by juliangruber** [comment]
Ah ok. Fuck git submodules :D 

Except for the mentioned failing test, tests pass on my mac with `0.10.38`, `0.12.1` and `1.6.2`. Great work!

@ralphtheninja did you test on linux?

**Comment by ralphtheninja** [comment]
@juliangruber I run linux, so yes ;)

**Comment by ralphtheninja** [comment]
@juliangruber While on the subject of tests. Should we remove the failing test? Not sure what the purpose of it is to be honest.

**Comment by juliangruber** [comment]
since it was failing before, noone complained and this is testing an internal detail (as far as i understand), i'd say yeah, let's remove it

**Comment by ralphtheninja** [comment]
@juliangruber I went through the code and the test that fails makes sure that `port_uv.h` is included. This means we do not fully support windows.

**Comment by juliangruber** [comment]
hm, let's move it to issues instead then

**Comment by rvagg** [comment]
@ralphtheninja fyi I've added you to leveldown-hyper, leveldown-bash, level-hyper and level-basho on npm

**Comment by ralphtheninja** [comment]
@rvagg Awesome!

**Comment by ralphtheninja** [comment]
Merging this now. I might publish a `next` version before going live with `leveldown-hyper@0.10.5`.

**Pull request merged**
