### PR TITLE
Add missing iojs 3.0 stuff

### PR DESCRIPTION
**Pull request by mafintosh**

### CODE REVIEW

**Comment by mafintosh** [comment]
Can anyone grok why travis doesn't like iojs 3.0.0 with leveldown? It works when I compile it locally on linux

**Comment by ralphtheninja** [comment]
cc @rvagg @kkoopa

**Comment by kkoopa** [comment]
Wrong compiler version. Needs at least gcc 4.8.

**Comment by mafintosh** [comment]
@kkoopa how do we fix that on travis?

**Comment by kkoopa** [comment]
```yaml
sudo: false
language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
```

**Comment by juliangruber** [comment]
should this be another patch level release, @mafintosh?

**Pull request merged**
