### PR TITLE
feat(typings): add initial typings

### PR DESCRIPTION
**Pull request by MeirionHughes**
* based off `master` README.md API
* levelup tests can pass when these leveldown typings are available.

### CODE REVIEW

**Comment by MeirionHughes** [comment]
⚠️ causes levelup test to fail. https://github.com/Level/levelup/blob/master/test/idempotent-test.js#L38

test passes through a cb, but the leveldown implementation doesn't use it: 

https://github.com/Level/leveldown/blob/master/leveldown.js#L11-L15

**Comment by ralphtheninja** [comment]
I'll get this merged and releases as soon as travis and appveyor have calmed down a bit :)

**Comment by MeirionHughes** [comment]
travis seems to have been stuck all day on this one. odd.

**Comment by ralphtheninja** [comment]
Screw travis. The package.json parses fine in my head :)

**Comment by ralphtheninja** [comment]
1.8.0 (but not published yet, travis have to finish first)

**Comment by ralphtheninja** [comment]
Not sure what happened with the travis build. Travis failed to find a ref so I canceled the rest. Funny though, that AppVeyor is superfast now and travis is slow as dirt. It's usually the other way around.

**Pull request merged**
