### PR TITLE
upgrade to leveldb-1.19

### PR DESCRIPTION
**Pull request by juliangruber**
This is a work in progress pull request for https://github.com/Level/leveldown/issues/298

The build is currently failing.

### CODE REVIEW

**Comment by juliangruber** [comment]
Build and tests now pass in my setup!

**Comment by juliangruber** [comment]
We should create a .patch file for the floating port_uv.h patch

**Comment by juliangruber** [comment]
Tests pass now on travis too. We can decide about adding new features in another pull request.

What do you all think? Should we do more manual testing? Manual inspection?

**Comment by ralphtheninja** [comment]
:100:

**Comment by chjj** [comment]
@juliangruber, great work.

Maybe we can merge it in to master, but hold off on publishing to npm for a little while? Either way, I'll be testing this thoroughly in practice for the next few days.

**Comment by ralphtheninja** [comment]
@juliangruber I guess this would mean a `1.4.7` release right? When we're ready we should ping @mafintosh for builds. Maybe we should try to muster some prebuilts for windows as well.

**Comment by vweevers** [comment]
Build and tests pass on Windows too. I can provide Windows prebuilds when the time comes.

**Comment by No9** [comment]
Thanks for this @juliangruber - builds and passes on my illumOS based distro

**Comment by ralphtheninja** [comment]
> Build and tests pass on Windows too. I can provide Windows prebuilds when the time comes.

:+1:

**Comment by ralphtheninja** [comment]
Builds and tests pass on Debian Jessie.

**Comment by juliangruber** [comment]
This sounds great!

I would just leave this here and wait for @chjj's tests results, then merge and release. (it's easy to by mistake release something when it's already in master)

By SemVer standard yeah it should be 1.4.7, but by "slightly personal meaningful semver" standard it should be 1.5.0

**Comment by mafintosh** [comment]
Great job @juliangruber. I think we should leave the PR open for a few days and then merge + release it next week assuming nothing catastrophic appears.

**Comment by ralphtheninja** [comment]
> By SemVer standard yeah it should be 1.4.7, but by "slightly personal meaningful semver" standard it should be 1.5.0

+1 Makes sense.

**Comment by rvagg** [comment]
This is interesting:

>   // EXPERIMENTAL: If true, append to existing MANIFEST and log files
>  // when a database is opened.  This can significantly speed up open.
>  //
>  // Default: currently false, but may become true later.
>  bool reuse_logs;

We could enable an undocumented option for this to allow for experimentation. The one problem I see here is that it uses a new `NewAppendableFile` API in `Env` which would probably have to be implemented in `port-libuv/env_win.cc` because even though the documentation says: `Users of Env (including the leveldb implementation) must be prepared to deal with an Env that does not support appending.` I don't believe it does properly deal with that case!

**Comment by rvagg** [comment]
PR LGTM except for two nits:
* remove .travis.yml ?
* chmod all files to 644, they are currently 755

**Comment by juliangruber** [comment]
> remove .travis.yml ?
> chmod all files to 644, they are currently 755

@rvagg why?

**Comment by chjj** [comment]
Update: I've been using this branch in practice for a little while now. I've sync'd the entire blockchain with it. Works great.

**Comment by rvagg** [comment]
> > remove .travis.yml ?
> > chmod all files to 644, they are currently 755

> @rvagg why?

1. Unnecessary churn, otherwise it's mostly a git rename and not an additional property change
2. These files are not executable and it's incorrect for them to have execute bit set on them except for `*.sh`

**Comment by juliangruber** [comment]
@rvagg this might sound stupid but, ...?

screen shot 2016-08-26 at 11 27 00

also, in current master the deps are already 755

**Comment by rvagg** [comment]
`find deps/leveldb -type f -exec chmod 644 '{}' \; && find deps/leveldb -type d -exec chmod 755 '{}' \;`

I'm sure there's some neat umasky way of doing it but that's how I'd do it. Files 644, directories 755.

**Comment by juliangruber** [comment]
gotcha, should all be addressed now!

**Comment by juliangruber** [comment]
Final call for @chjj, I'm assuming everything looks good so far?

@ralphtheninja @mafintosh @vweevers how do we orchestrate publishing the prebuilds? Do you want to send yours to me so I can release and upload in one go?

**Comment by vweevers** [comment]
@juliangruber I can get #309 going, once we reach consensus on:

> Tagged commits trigger an upload to GitHub. Which means the AppVeyor job will be the first to create a GH release, whenever someone pushes a tag. Does anyone foresee problems with that? Alternatively, we can manually download artifacts from AppVeyor and attach them to a GH release. WDYT?

**Comment by chjj** [comment]
I can only speak from my own use here: this works perfectly on every x64 linux machine I've tried it on. Merging sounds good to me.

**Comment by ralphtheninja** [comment]
> @ralphtheninja @mafintosh @vweevers how do we orchestrate publishing the prebuilds? Do you want to send yours to me so I can release and upload in one go?

@juliangruber I'd suggest you sync with @mafintosh so he can push the button on linux and osx. Then we can build for arm and windows and update.

**Comment by ralphtheninja** [comment]
@juliangruber Can we bump some dependencies before releasing? I'm mainly thinking of the `abstract-leveldown` fix you made the other day.

**Comment by juliangruber** [comment]
@ralphtheninja sure! do you want to make a pull request for that?

**Pull request merged**
