### PR TITLE
add node 8 to travis and appveyor

### PR DESCRIPTION
**Pull request by ralphtheninja**
Closes https://github.com/Level/leveldown/issues/365

### CODE REVIEW

**Comment by ralphtheninja** [comment]
@vweevers I noticed that the `0.12` build failed because npm doesn't support it :angry: Is 0.12 dead now? Or should we downgrade npm so we can support it?

**Comment by vweevers** [comment]
@ralphtheninja let's try removing the `npm -g i npm@latest` line from `appveyor.yml`, I don't think it's required anymore. Then it'll just use the npm version that's bundled with node.

**Comment by ralphtheninja** [comment]
Nevermind. Just checked https://github.com/nodejs/LTS/ and it seems maintenance ended last year. I'm all for not supporting prebuilts for 0.12, but if someone else still wants to support I don't have a strong opinion against it.

**Comment by ralphtheninja** [comment]
I can remove the `npm -g i npm@latest` first as you suggested and we can discuss 0.12 in another issue.

**Comment by vweevers** [comment]
Looking good.

Question: since node 8, `new Buffer(num)` and `Buffer(num)` will zero-fill new Buffer instances. Any chance this affects leveldown or the level* ecosystem?

**Comment by juliangruber** [comment]
> Question: since node 8, new Buffer(num) and Buffer(num) will zero-fill new Buffer instances.

> Any chance this affects leveldown

Unlikely. I just did a quick look through `leveldown` and `abstract-leveldown` and couldn't find any problematic `Buffer` usage.

> or the level* ecosystem?

Quite likely. The `level*` ecosystem is quite huge and I wouldn't be surprised if some module used `new Buffer(n)` for random string generation. Not our concern however.

**Comment by ralphtheninja** [comment]
1.7.1

And _yes_ I will wait with publish until both travis and appveyor are done ;) tickle @vweevers

**Pull request merged**
