### PR TITLE
Fixes #247

### LINKED ISSUE #213: Leveldown failing to compile on win 10
Hello everyone!

I'm trying to install level and it fails at installing leveldown. I have windows 10 and visual studio 2015 (newly installed) also the newest node-gyp (v2.0.2) Nodejs is 0.12.7 my pc is a 64bits system. The headers are not missing and there are placed in the correctly.
[npm-debug.log](https://mega.nz/#!OVQmTDjL!MVdGlkwVwE2RPpNHF2yAtIyqByDtpTSOLcvnaknaWOE)
image
image

### LINKED ISSUE #247: Compiler error when using Visual Studio 2015 on Windows 7
```
d:\home\js\modules_by_npm\node_modules\leveldown\deps\leveldb\port-libuv\stdint-msvc2008.h(109): error C2371: 'uint_fast16_t': red efinition; different basic types (compiling source file leveldb-1.18.0\db\filename.cc) [D:\home\js\modules_by_npm\node_modules\lev eldown\deps\leveldb\leveldb.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\stdint.h(40): note: see declaration of 'uint_fast16_t' (compiling
   source file leveldb-1.18.0\db\filename.cc)
```
The errors are like the above.
I modify some part of deps\leveldb\port-libuv\port_uv.h from
```
#elif defined(_MSC_VER)
  #include "stdint-msvc2008.h"
  #define PLATFORM_IS_LITTLE_ENDIAN true
  #define snprintf _snprintf
```
to
```
#elif defined(_MSC_VER)
// MSVC++ 14.0 _MSC_VER == 1900 (Visual Studio 2015)
#if _MSC_VER < 1900
  #include "stdint-msvc2008.h"
#endif
  #define PLATFORM_IS_LITTLE_ENDIAN true
#if _MSC_VER < 1900
  #define snprintf _snprintf
#endif
```
Then the compilation is OK.
Is it the correct solution?
It would be nice if the problem is fixed.

### PR DESCRIPTION
**Pull request by obastemur**
Most probably also fixes #213

### CODE REVIEW

**Comment by ralphtheninja** [comment]
This fix seems to be what @No9 proposed here https://github.com/Level/leveldown/issues/213#issuecomment-134424372

+1

**Comment by obastemur** [comment]
Good catch. Indeed it is. With a minor difference of vs2013 support. I had fixed leveldown mobile along with the Windows UWP support but forgot sending a PR here.

**Comment by ralphtheninja** [comment]
> Good catch. Indeed it is. With a minor difference of vs2013 support. I had fixed leveldown mobile along with the Windows UWP support but forgot sending a PR here.

Has leveldown mobile worked well with these changes?

**Comment by obastemur** [comment]
AFAIK yes. i.e. JXcore WinARM release embeds leveldown.

**Comment by ralphtheninja** [comment]
1.4.4, prebuilds coming shortly

**Pull request merged**
