### PR TITLE
release iterator snapshots. free up iterator slices.

### PR DESCRIPTION
**Pull request by chjj**
I think I may have fixed the memory problem I was having with iterators. It looks like ReleaseSnapshot was defined but never called anywhere after an iterator was ended.

### CODE REVIEW

**Comment by chjj** [comment]
cc @ralphtheninja @rvagg

**Comment by ralphtheninja** [comment]
Looks good to me but I can't say that I have this fresh in my head so just gonna do some rubber ducking.

So, `Iterator::IteratorEnd` is called from `EndWorker::Execute`, which is a result of calling `iter->end()` in js land right? Then there's `Iterator::Release` which is called from `EndWorker::HandleOKCallback`, which does `database->ReleaseIterator(id)`. Why do we have two similar release calls scattered in two places? ISTM that `database->ReleaseSnapshot(options->snapshot)` belong together with `database->ReleaseIterator(id)`.

**Comment by chjj** [comment]
It looks like database->IteratorRelease is doing some v8 stuff, whereas `delete dbIter` and ReleaseSnapshot (in `IteratorEnd()`) does leveldb stuff, so it makes sense for those last two to be on the thread pool where database->IteratorRelease happens in OKCallback.

**Comment by chjj** [comment]
Totally not relevant, but I feel the need to share my story after all this work to find memleaks: I had an epiphany when I was writing an [in-memory BST][1] as a replacement for memdown (I wanted something iterative, and I didn't like all the recursive calls the rb tree was making). It's a destructive bst, so if I wanted to implement a real iterator, I had to take a snapshot before traversing the tree if I wanted any sort of consistency. I looked at the code and thought I should probably `null` the snapshotted root node once the iterator ended to hopefully free up memory faster. Then it hit me like a ton of bricks: leveldown might not be freeing up its snapshot, and sure enough, it wasn't. :)

[1]: https://github.com/bcoin-org/bcoin/blob/master/lib/bcoin/bst.js

**Comment by chjj** [comment]
Also including my latest memleak fix here. See #272. Needs review.

**Comment by chjj** [comment]
@dominictarr, would you mind testing this PR with the memleak example I wrote? I'm not seeing a leak on the native heap, but the js heap seems to be abnormally large for me (around 40mb allocated, 8-25mb used). I'm just curious where your v8 heap is still around ~20mb with this patch.

**Comment by chjj** [comment]
Yeah, looks like passing the startHandle every time is causing v8 to defensively expand its heap. Since that's only necessary for Buffers, it might just be better to copy the buffer (if there is one) onto a new string and just delete it without the DisposeXX call.

**Comment by chjj** [comment]
Hmm, with my old code it looks like the js heap is about 7mb smaller for me. v8 is probably defensively expanding its heap because of the startHandle getting passed into persistentHandle. It might be more performant to just copy a buffer onto a new char array and unconditionally free it on destruction since that startHandle really seems to only be an optimization for Buffer keys here.

**Comment by chjj** [comment]
Alright guys, my latest commit appears to make iterators MUCH more efficient. It simply copies the Buffer (if there is one, unlikely) and avoids passing a startHandle to the Iterator object. Also, 99% of the time it will avoid allocating an extra string like it was doing before. This has _halved_ the memory usage when running my [test case][1].

[1]: https://github.com/Level/leveldown/issues/272

**Comment by mafintosh** [comment]
@chjj @ralphtheninja this looks LGTM from me. great job everyone.

**Comment by ralphtheninja** [comment]
@chjj Great work. Lets get this released today. I just want to try it out first :)

**Comment by ralphtheninja** [comment]
1.4.5

**Pull request merged**
