### PR TITLE
bump dependencies

### PR DESCRIPTION
**Pull request by ralphtheninja**

### CODE REVIEW

**Comment by ralphtheninja** [comment]
@mafintosh Ping me when you have a minute to release 1.4.3 :)

**Comment by ralphtheninja** [comment]
1.4.3

**Comment by mafintosh** [comment]
@ralphtheninja i'm ready

**Comment by ralphtheninja** [comment]
@mafintosh Cool. Fire away :)

**Comment by mafintosh** [comment]
@ralphtheninja uploaded builds for osx and 32+64 bit linux

**Comment by No9** [comment]
Win X64 up 
Win x32/illumos and some freebsd on there way

**Comment by mafintosh** [comment]
we need a bat-signal module to signal all the leveldown builders

**Comment by mafintosh** [comment]
https://www.npmjs.com/package/bat-signal

**Comment by ralphtheninja** [comment]
> we need a bat-signal module to signal all the leveldown builders

Hehe would be really cool. Basically ping everyone on all available channels? Twitter? Irc? :)

**Comment by ralphtheninja** [comment]
> Win X64 up
> Win x32/illumos and some freebsd on there way

Nice :)

**Pull request merged**
