### PR TITLE
run verify-travis-appveyor as part of tests and before prebuild-ci

### PR DESCRIPTION
**Pull request by ralphtheninja**

### CODE REVIEW

**Comment by vweevers** [comment]
Nice! Can you make a temporary commit here to demonstrate a failing build? Because I understand the module has no unit tests for inconsistenties yet (https://github.com/ralphtheninja/verify-travis-appveyor/issues/1).

**Comment by ralphtheninja** [comment]
@vweevers Aaah, good idea!

**Comment by ralphtheninja** [comment]
I'll let these builds pass first and then make another temp commit where appveyor is inconsistent with travis. I'll start working on those tests after that.

**Comment by vweevers** [comment]
@ralphtheninja It's failing for a different reason: https://travis-ci.org/Level/leveldown/jobs/336671818#L819-L820

**Comment by vweevers** [comment]
> Also I broke appveyor on some builds because of the second commit.

I noticed that too. Apparently AppVeyor checks out `HEAD` rather than a specific commit. I never knew that :/

**Comment by ralphtheninja** [comment]
I'm gonna close this PR out and play around in `ralphtheninja/leveldown`

**Comment by ralphtheninja** [comment]
@vweevers Found this https://github.com/travis-ci/travis-ci/issues/6307 which might be related

**Comment by ralphtheninja** [comment]
If tried removing `faucet` temporarily because I think it messes up output

https://travis-ci.org/ralphtheninja/leveldown/jobs/336684972

So it does fail correctly, but the last line about `shell_session_update` is confusing.

**Comment by vweevers** [comment]
@ralphtheninja in the issue you referenced, people are saying that any non-zero exit code is a problem. The accepted solution seems to be https://github.com/travis-ci/travis-ci/issues/6307#issuecomment-350725425, though later comments say that it no longer works.

**Comment by ralphtheninja** [comment]
Oh sheesh. The amount of yak-shaving is endless.

**Pull request closed without merging**
