### PR TITLE
revert changes for node-pre-gyp

### PR DESCRIPTION
**Pull request by ralphtheninja**

### CODE REVIEW

**Comment by mafintosh** [comment]
:+1:

**Comment by juliangruber** [comment]
is this really just one change? looks suspicious, like merging from or into a wrong branch. if not, just ignore me

**Comment by ralphtheninja** [comment]
@juliangruber Yes. Basically we're reverting what we did with `node-pre-gyp` (package.json). Let me add some comments.

**Comment by ralphtheninja** [comment]
I'll merge this tomorrow.

**Comment by ralphtheninja** [comment]
Actually, I'll merge this now :)

**Pull request merged**
