### PR TITLE
Upgrade LevelDB 1.18.0

### LINKED ISSUE #157: Segfault on close with pending put
I am getting a segfault when I run the following unit test.  The segfault doesn't happen every time I run the test.  Any ideas?

``` javascript
var test        = require('tape');
var level       = require('level');
var path        = require('path');
var through2    = require('through2');
var JSONStream  = require('JSONStream');

function push(db) {

    return through2.obj(function(levelRequest, enc, cb) {

        var self = this;

        db.put(levelRequest.key, levelRequest.value, {sync:true}, function(error) {
            if (error) {
                console.log('encountered an error while putting ' + JSON.stringify(levelRequest) + ' on the database: '
                            + error);
                self.push({result:'error', key: levelRequest.key, msg: error});
            } else {
                self.push({result:'success', key: levelRequest.key});
            }
            cb();
        });

    })

}

test('can push values through a level database', function(t) {
    var db   = level('./test.db');

    var dbify = push(db);
    var stringify = JSONStream.stringify(false);

    dbify.pipe(stringify).pipe(process.stdout);

    dbify.write({key:'hi', value:"wisconsin"});

    db.close(function(er) {
        if (er) throw er;
        t.end();
    })

})
```

### PR DESCRIPTION
**Pull request by braydonf**
~~Upgrading to LevelDB 1.18.0 seems to resolve issue https://github.com/Level/leveldown/issues/157~~

Edit: Scratch that, doesn't resolve #157

### CODE REVIEW

**Comment by ralphtheninja** [comment]
:+1:

**Comment by ralphtheninja** [comment]
This entitles a `npm version minor`. Someone else care to have a look? :) /cc @Level/owners

**Comment by braydonf** [comment]
Probably a good idea to upgrade anyways though :) Still not sure what the issue is with #157. I had a modified version of levelup that prevented close from being called until put was finished, but that should likely be handled in leveldown (and it looks like that's how it's supposed to work).

**Comment by ralphtheninja** [comment]
I believe the issue with #157 is a race condition. The db is destroyed before operations that are in flight have finished. It's a known issue.

**Comment by juliangruber** [comment]
lgtm, and +1 for minor

**Comment by ralphtheninja** [comment]
@braydonf Mind rebasing this onto latest master? Time to update this baby now!

**Comment by braydonf** [comment]
Rebased

**Comment by juliangruber** [comment]
cheers! published as 1.3.0

**Pull request merged**
