### PR TITLE
Support compilation on iOS 

### PR DESCRIPTION
**Pull request by agentilela**
Add support for iOS compilation to enable use cases like: https://github.com/janeasystems/nodejs-mobile/issues/64

### CODE REVIEW

**Comment by vweevers** [comment]
@ralphtheninja @juliangruber what's our policy on modifying vendored code (`deps/`)?

**Comment by juliangruber** [comment]
I think if we want to merge this we should keep a patch around, ready to be applied to new versions of vendored code. Didn't we have something like this before?

**Comment by ralphtheninja** [comment]
> @ralphtheninja @juliangruber what's our policy on modifying vendored code (deps/)?

We don't have one. Ideally these changes should be made upstream imo and later pulled in.

> I think if we want to merge this we should keep a patch around, ready to be applied to new versions of vendored code.

+1

> Didn't we have something like this before?

I can't remember having something like this around. I might be wrong though. Should be visible in the CHANGELOG.

**Comment by vweevers** [comment]
For the record, since #446, we do have a "policy" :)

Who can review this?

**Comment by ralphtheninja** [comment]
3.0.2

**Pull request merged**
