### PR TITLE
chore(package): update prebuild to version 3.0.0

### PR DESCRIPTION
**Pull request by ralphtheninja**

### CODE REVIEW

**Comment by juliangruber** [comment]
re-running the tests, the node 4 failure looks weird

**Comment by juliangruber** [comment]
ewwww it crashed!

**Comment by ralphtheninja** [comment]
lolwut? o.O I've never seen something like that before.

**Comment by ralphtheninja** [comment]
Just tried with 4.3.0 on my machine. Works just fine. Hammer time!

**Pull request merged**
