### PR TITLE
rocksdb refresh

### PR DESCRIPTION
**Pull request by cjihrig**
The current rocksdb module was published four years ago. In April of this year, I brought it up to date with a recent rocksdb, nan, etc. It turns out I'm not going to have any use for it, so I wanted to offer it back to the level community. If you want it, great. If not, feel free to close the PR.

Sorry, but this doesn't merge cleanly, and would probably require a force push. You can check out the most recent three commits for my changes.

cc: @mcollina

### CODE REVIEW

**Comment by mcollina** [comment]
I think this is due to the rocksdb branch being done as a fork, while this one started from scratch from master, is it correct?

Thanks @cjihrig, I'm taking over from now.

@ralphtheninja @juliangruber let me know how you'd want to approach this. I think we can rename the old one "rocksdb-legacy", and use this.

**Comment by ralphtheninja** [comment]
@mcollina Iirc the rocksdb stuff is in the `rocksdb` branch (and not a fork) inside leveldown similar to `hyper-leveldb`, which I extracted to the fork https://github.com/Level/leveldown-hyper a while ago. Maybe take this stuff and push to a new repo, e.g. `leveldown-rocksdb`?

**Comment by ralphtheninja** [comment]
I might have misunderstood the fork thing, sorry for the confusion :)

**Comment by mcollina** [comment]
I meant the branch. I've called it a fork because it is released on its own module, and it has diverged from
master

**Comment by cjihrig** [comment]
> I think this is due to the rocksdb branch being done as a fork, while this one started from scratch from master, is it correct?

I think I understand your question. The existing rocksdb branch was so out of date that it was easier to start from an up to date version of leveldown than to update the existing branch.

**Comment by juliangruber** [comment]
tbqh i'm out of maintaining rocksdb

**Comment by ralphtheninja** [comment]
> I think I understand your question. The existing rocksdb branch was so out of date that it was easier to start from an up to date version of leveldown than to update the existing branch.

This is the same approach I took when getting the hyperdb fork up to date.

**Comment by mcollina** [comment]
@ralphtheninja how do you want to proceed? If you'd like I can do the publishing work.

**Comment by ralphtheninja** [comment]
> @ralphtheninja how do you want to proceed? If you'd like I can do the publishing work.

Just create a new repo on level org and push this branch as master to that repo?

**Comment by ralphtheninja** [comment]
@mcollina We can start there at least :)

**Comment by mcollina** [comment]
I'll do that asap.

**Comment by mcollina** [comment]
I'm currently getting a

```
make: *** No rule to make target `Release/obj.target/leveldb/deps/leveldb/leveldb-rocksdb/util/build_version.o', needed by `Release/leveldb.a'.  Stop.
```

as it fails the build.

**Comment by cjihrig** [comment]
What version of node? `rm -rf node_modules/; npm i; npm test` worked for me with node 7.7.1 on macOS.

**Comment by cjihrig** [comment]
Closing this as the commits are now at https://github.com/Level/rocksdb.

**Pull request closed without merging**
