### PR TITLE
make 0.10.x play nice with node 4 and 5

### PR DESCRIPTION
**Pull request by ralphtheninja**
Fixes https://github.com/Level/leveldown/issues/244

### CODE REVIEW

**Comment by ralphtheninja** [comment]
So now it builds for node 3, 4 and 5 but not for older versions. Wat? o.O

build-results

**Comment by ralphtheninja** [comment]
There we go.

**Comment by ralphtheninja** [comment]
@Level/owners Could I get some eyes on this just for sanity checks?

**Comment by juliangruber** [comment]
+1

**Pull request merged**
