### PR TITLE
re #268, #270, updated version of leveldb from google/leveldb master

### PR DESCRIPTION
**Pull request by myf**
- deps/leveldb/leveldb-1.18-ea992b467b9f3c892ae87267ba908e97d532b1b2/ is
pulled from the master branch of https://github.com/google/leveldb at
commit ea992b467b9f3c892ae87267ba908e97d532b1b2

- added LEVELDB_PLATFORM_UV line in port/port.h

- modified leveldb.gyp for the new version and renamed
db/leveldb_main.cc to db/leveldbutil.cc as modified by google

### CODE REVIEW

**Comment by myf** [comment]
@rvagg google/leveldb v1.18 was published 2 years ago, however there are quite a few improvements since then, including the support for `ARMv8` and `MIPS` support which dated as far back as 2014. It would be great if we upgrade leveldown when leveldb v1.19 comes out but I have no idea how far down the road this would happen.

this pr pulled the latest master of google/leveldb at commit ea992b467b9f3c892ae87267ba908e97d532b1b2, with modified `port.h` to include port_uv and also modified `leveldb.gyp` to change a file name from `leveldb_main.cc` to `leveldbutil.cc` based on upstream. 

The build succeeded and all the tests passed. On my odroid c2 the build was working properly to support `ARMv8`.

This is an alternative to pull request #270 to support ARMv8 and MIPS. Instead the entire leveldb directory is updated to the latest master. Also since google/leveldb is it's own repository, should we do `git submodules` instead?

please comment :)

**Comment by martinheidegger** [comment]
1.19 has since been published. It might be good to update this PR?

**Comment by myf** [comment]
@martinheidegger you are right, since 1.19 is merged into the master this PR was intended to fix the same thing before the release of 1.19. will close after i test it on my `AARCH64` system :)

**Comment by myf** [comment]
this is fixed with https://github.com/Level/leveldown/pull/299 that pulls leveldb 1.19 which added `AARCH64` and `MIPS` as supported platforms.

**Pull request closed without merging**
