### PR TITLE
add options: filterBits, paranoidChecks, and memory.

### PR DESCRIPTION
**Pull request by chjj**
Just thought these options should be in here.

### CODE REVIEW

**Comment by chjj** [comment]
Hmm, looks like we have to add verify_checksums to the read options too.

**Comment by chjj** [comment]
Added a `memory` option for in-memory databases.

**Comment by ralphtheninja** [comment]
@chjj Mind rebasing this onto latest master?

**Comment by ralphtheninja** [comment]
This would have to be re-implemented since we're now based on n-api.

**Pull request closed without merging**
