### PR TITLE
Prepare nan 2.0

### PR DESCRIPTION
**Pull request by ralphtheninja**
Closes https://github.com/Level/leveldown/issues/175

### CODE REVIEW

**Comment by juliangruber** [comment]
lgtm

**Comment by mcollina** [comment]
Should we backport this into 0.10.x? Is it needed to run on newer iojs
releases?
Il giorno sab 9 mag 2015 alle 15:00 Julian Gruber <notifications@github.com>
ha scritto:

**Comment by ralphtheninja** [comment]
@mcollina I don't think that's needed. `0.10.x` can just keep using the version of nan it uses right now. This will be needed once we decide to step onto `nan@2.0`

**Comment by ralphtheninja** [comment]
@mcollina Correction. It's not needed right now. It might be in the future though, depending on what happens with iojs. Lets backport when/if we really need it. We want people to start using the latest `levelup`/`leveldown` as well.

**Comment by ralphtheninja** [comment]
@rvagg Does this look ok?

**Comment by kkoopa** [comment]
To clarify, the OptionValue routines will be deprecated in NAN 1.9 (last of the 1-series, yet unreleased). They will be removed completely in NAN 2.0.

**Comment by ralphtheninja** [comment]
@kkoopa Thanks for heads up. This should be merged long before that happens :)

**Pull request merged**
